name: Execute template to populate repository

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup-repo:
    if: ${{ github.repository != 'falcopackages/starter-template' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install falco-cli
        run: uv tool install falco-cli --pre -c next-release


      - uses: actions/github-script@v7
        id: fetch-repo-and-user-details
        with:
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name) {
                name
                description
                owner {
                  login
                  ... on User {
                    name
                    email
                  }
                  ... on Organization {
                    name
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo
            }
            const result = await github.graphql(query, variables)
            console.log(result)
            return result

      - name: Rebuild contents using falco-cli
        env:
          INFO: ${{ steps.fetch-repo-and-user-details.outputs.result }}
        run: |
          export REPO_NAME=$(echo $INFO | jq -r '.repository.name')
          export AUTHOR_NAME=$(echo $INFO | jq -r .repository.owner.name)
          export AUTHOR_EMAIL=$(echo $INFO | jq -r .repository.owner.email)
          export DESCRIPTION="$(echo $INFO | jq -r .repository.description | sed 's/\"/\\\"/g')"
          export USERNAME="$(echo $INFO | jq -r .repository.owner.login)"
          # Run falco-cli
          pushd /tmp
          falco start-project $REPO_NAME
          popd
          # Move generated content to root directory of repo
          mv /tmp/$REPO_NAME/* .
          # And .gitignore too:
          mv /tmp/$REPO_NAME/.gitignore .
          # Delete the setup.yml workflow, it has served its purpose
          rm .github/workflows/setup.yml
          # format the code
          just lint || true

      - name: Force push new repo contents
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Initial commit"
          push_options: --force
